services:
    app:
        image: dakardu/netservices:latest
        ports:
            - "80:80"
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped

    db:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

volumes:
    db_data:
        driver: local
