version: "3.8"

services:
    app:
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
            - .db:/docker-entrypoint-initdb.d/

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASSWORD}

volumes:
    db_data:
